import Head from 'next/head'

type Props = {
  title: string
}

const fuba = 'teste'

export default function Home({ title = 'Next JS Boilerplate' }: Props) {
  return (
    <div>
      <Head>
        <title>{title}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main></main>

      <footer></footer>
    </div>
  )
}
